# yaml-language-server: $schema=../../json/neu-sch.json
$ref: '#/Config'
Config:
  type: object
  $comment: |
    The presence of 'EXCLUDED_IN_MD' in the '$comment' field prevents Markdown generation of the schema
  properties:
    applicationId:
      type: string
      default: js.neutralino.sample
      description: |
        Unique string to identify your application. Eg: `js.neutralino.sample`
    defaultMode:
      type: string
      enum:
        - window
        - browser
        - cloud
      default: window
      description: |
        Mode of the application. Accepted values are `window`, `browser`, and `cloud`.
    port:
      type: integer
      description: |
        The port of your application. If the value is `0`, Neutralinojs will use a random available port.
    url:
      type: string
      description: |
        The entrRLy U of the application. Neutralinojs will initially load this URL.
        This property accepts both relative and absolute URLs.
      default: /resources/
    enableHTTPServer:
      type: boolean
      description: |
        Enables or disables the background server (The static file server and native API).
      default: true
    enableNativeAPI:
      type: boolean
      description: |
        Enables or disables the native API. For better security, this setting should be `false` if you are using a
        remote URL as your web frontend.
      default: true
    nativeBlockList:
      type: array
      description: |
        An array of native methods needs to be blocked from the frontend of the application.
      items:
        type: string
    globalVariables:
      $ref: '#/ConfigGlobals'
    modes:
      $ref: '#/ConfigModes'
    cli:
      $ref: '#/ConfigCli'
  required:
    - applicationId
    - defaultMode
    - port
    - url
    - enableHTTPServer
    - enableNativeAPI
    - nativeBlockList
    - globalVariables
    - modes
    - cli

ConfigGlobals:
  type: object
  properties: {}
  description: |
    A key-value-based JavaScript object of custom [global variables](../developer-environment/global-variables#custom-global-variables).

ConfigModes:
  type: object
  properties:
    window:
      $ref: '#/ConfigModeWindow'
    browser:
      $ref: '#/ConfigModeBrowser'
    cloud:
      $ref: '#/ConfigModeCloud'
  required:
    - window
    - browser
    - cloud

ConfigModeWindow:
  type: object
  required:
    - title
  properties:
    title:
      type: string
      default: Neutralinojs app
      description: Title of the native window.
    width:
      type: integer
      default: 800
      description: Width of the native window.
    height:
      type: integer
      default: 500
      description: Height of the native window.
    maxWidth:
      type: number
      description: Maximum width of the native window.
    maxHeight:
      type: number
      description: Maximum height of the native window.
    minWidth:
      type: integer
      default: 400
      description: Minimum width of the native window.
    minHeight:
      type: integer
      default: 200
      description: Minimum height of the native window.
    fullScreen:
      type: boolean
      default: false
      description: Activates the full-screen mode.
    alwaysOnTop:
      type: boolean
      default: false
      description: Activates the top-most mode.
    icon:
      type: string
      default: /resources/icons/appIcon.png
      description: |
        Application icon's file name. You can directly point to an image file in the
        resources directory. We recommend you to choose a transparent PNG file.
    enableInspector:
      type: boolean
      default: true
      description: Automatically opens the developer tools window.
    borderless:
      type: boolean
      default: false
      description: Activates the borderless mode.
    maximize:
      type: boolean
      default: false
      description: Launches the application maximized.
    hidden:
      type: boolean
      default: false
      description: |
        Make the window invisible. This setting can be used to develop background services.
    resizable:
      type: boolean
      default: true
      description: |
        Make the window resizable or not. The default value is `true`.

ConfigModeBrowser:
  type: object
  properties: {}

ConfigModeCloud:
  type: object
  properties: {}

ConfigCli:
  type: object
  required:
    - binaryName
    - resourcesPath
    - clientLibrary
  properties:
    binaryName:
      type: string
      description: |
        Binary file name of your application. If it is `myapp`, all binaries should use
        `myapp-<platform>` format.
      default: neutralino
    resourcesPath:
      type: string
      description: |
        Path of your application resources.
      default: /resources/
    clientLibrary:
      type: string
      default: /resources/js/neutralino.js
      description: |
        Filename of the Neutralinojs JavaScript library.
    binaryVersion:
      type: string
      description: |
        Neutralinojs server version. neu CLI adds this property when the project is scaffolded.
    clientVersion:
      type: string
      description: |
        Neutralinojs client version. neu CLI adds this property when the project is scaffolded.
  