# yaml-language-server: $schema=../json/neu-api.json
$namespace: Neutralino.app
$description: |
  `Neutralino.app` namespace contains methods related to the current application instance.

src-ref: |
  https://github.com/neutralinojs/neutralinojs.github.io/blob/main/docs/api/app.md
  https://github.com/neutralinojs/neutralinojs/blob/main/api/app/app.cpp
  https://github.com/neutralinojs/neutralino.js/blob/main/src/api/app.ts

#

exit:
  type: http:post
  params:
    $ref: '#/ExitParams'
  result:
    $ref: '#/ExitResult'
  description: |-
    Terminates the running application.

    ```js
    await Neutralino.app.exit();
    ```

    ```js
    await Neutralino.app.exit(130);
    ```

ExitParams:
  type: object
  properties:
    code:
      type: integer
      description: An integer value for the process's exit code. The default value is always `0` (success).

ExitResult:
  type: object
  properties:
    success:
      type: boolean
  required:
    - success

#

getConfig:
  type: http:get
  result:
    $ref: '#/GetConfigResult'
  description: |-
    Returns the current application configuration as a JSON object.

    ```js
    Neutralino.app.getConfig ()
    ```

GetConfigResult:
  type: object
  properties:
    returnValue:
      $ref: models/neutralino.config.schema.yaml

#

keepAlive:
  type: http:get
  result:
    $ref: '#/KeepAliveResult'
  description: |-
    The keepAlive method is responsible for saving the Neutralinojs server instance from the automatic termination.
    This method is called automatically from the client library for the browser mode.

    ```js
    Neutralino.app.keepAlive();
    ```   

KeepAliveResult:
  type: object
  properties:
    success:
      type: boolean
    message:
      type: string

#

killProcess:
  type: http:get
  result:
    $ref: '#/KillProcessResult'
  description: |-
    Kills the application process.
    If the application becomes unresponsive,
    you can use this to terminate the process instantly.
    It is recommended to use the `exit()` method to close your application properly.

    ```js
    await Neutralino.app.killProcess();
    ```

KillProcessResult:
  type: object
  properties:
    success:
      type: boolean
  required:
    - success

#

restartProcess:
  type: js:method
  params:
    $ref: '#/RestartOptions'

RestartOptions:
  type: object
  properties:
    args:
      type: string
